//! Embedded UI assets for browser chrome
//! Generated by tools/gen_placeholders.zig
//!
//! To regenerate: zig run tools/gen_placeholders.zig

pub const Theme = enum {
    dark,
    light,
};

/// Mouse cursor (16x16 white arrow with black outline)
pub const cursor = @embedFile("assets/cursor.png");

/// Dark theme assets
pub const dark = struct {
    // Navigation buttons (32x32)
    pub const back_normal = @embedFile("assets/dark/back-normal.png");
    pub const back_hover = @embedFile("assets/dark/back-hover.png");
    pub const back_active = @embedFile("assets/dark/back-active.png");
    pub const back_disabled = @embedFile("assets/dark/back-disabled.png");

    pub const forward_normal = @embedFile("assets/dark/forward-normal.png");
    pub const forward_hover = @embedFile("assets/dark/forward-hover.png");
    pub const forward_active = @embedFile("assets/dark/forward-active.png");
    pub const forward_disabled = @embedFile("assets/dark/forward-disabled.png");

    pub const refresh_normal = @embedFile("assets/dark/refresh-normal.png");
    pub const refresh_hover = @embedFile("assets/dark/refresh-hover.png");
    pub const refresh_active = @embedFile("assets/dark/refresh-active.png");
    pub const refresh_loading = @embedFile("assets/dark/refresh-loading.png");

    pub const close_normal = @embedFile("assets/dark/close-normal.png");
    pub const close_hover = @embedFile("assets/dark/close-hover.png");
    pub const close_active = @embedFile("assets/dark/close-active.png");

    // Full bars
    pub const tabbar_normal = @embedFile("assets/dark/tabbar-normal.png");
    pub const statusbar_normal = @embedFile("assets/dark/statusbar-normal.png");
};

/// Light theme assets
pub const light = struct {
    // Navigation buttons (32x32)
    pub const back_normal = @embedFile("assets/light/back-normal.png");
    pub const back_hover = @embedFile("assets/light/back-hover.png");
    pub const back_active = @embedFile("assets/light/back-active.png");
    pub const back_disabled = @embedFile("assets/light/back-disabled.png");

    pub const forward_normal = @embedFile("assets/light/forward-normal.png");
    pub const forward_hover = @embedFile("assets/light/forward-hover.png");
    pub const forward_active = @embedFile("assets/light/forward-active.png");
    pub const forward_disabled = @embedFile("assets/light/forward-disabled.png");

    pub const refresh_normal = @embedFile("assets/light/refresh-normal.png");
    pub const refresh_hover = @embedFile("assets/light/refresh-hover.png");
    pub const refresh_active = @embedFile("assets/light/refresh-active.png");
    pub const refresh_loading = @embedFile("assets/light/refresh-loading.png");

    pub const close_normal = @embedFile("assets/light/close-normal.png");
    pub const close_hover = @embedFile("assets/light/close-hover.png");
    pub const close_active = @embedFile("assets/light/close-active.png");

    // Full bars
    pub const tabbar_normal = @embedFile("assets/light/tabbar-normal.png");
    pub const statusbar_normal = @embedFile("assets/light/statusbar-normal.png");
};
